### ISSUE TITLE
ImportError: DLL load failed while importing sc2pathlib: The parameter is incorrect.

### ISSUE THREAD

**Issue by danielchen0** [DrInfy/sharpy-starter-bot#3]
```C:\Users\sirda\sharpy-starter-bot>python run_custom.py -m EverDreamLE -p1 zergbot -p2 ai
Traceback (most recent call last):
  File "run_custom.py", line 4, in <module>
    from protossbot.bot import ProtossBot
  File "C:\Users\sirda\sharpy-starter-bot\protossbot\bot.py", line 5, in <module>
    from sharpy.knowledges import KnowledgeBot
  File "sharpy-sc2\sharpy\knowledges\__init__.py", line 1, in <module>
    from .knowledge import Knowledge
  File "sharpy-sc2\sharpy\knowledges\knowledge.py", line 9, in <module>
    from sharpy.managers.core import *
  File "sharpy-sc2\sharpy\managers\__init__.py", line 1, in <module>
    from sharpy.managers.core.manager_base import ManagerBase
  File "sharpy-sc2\sharpy\managers\core\__init__.py", line 8, in <module>
    from .zone_manager import ZoneManager
  File "sharpy-sc2\sharpy\managers\core\zone_manager.py", line 6, in <module>
    import sc2pathlibp
  File "sharpy-sc2\sc2pathlibp\__init__.py", line 1, in <module>
    from .path_finder import PathFinder
  File "sharpy-sc2\sc2pathlibp\path_finder.py", line 1, in <module>
    from .sc2pathlib import PathFind
ImportError: DLL load failed while importing sc2pathlib: The parameter is incorrect.
```

What would this mean? I just downloaded the repo and pip installed the modules.

**Comment by danielchen0** [comment]
The command I ran is from Pycharm:
```C:\Users\sirda\sharpy-starter-bot>python run_custom.py -m EverDreamLE -p1 zergbot -p2 ai```

**Comment by danielchen0** [comment]
I have tried this now in a venv with configuration and just in the terminal (no venv) and get this both ways.

**Comment by danielchen0** [comment]
I am on Windows 10 if that matters?

**Comment by danielchen0** [comment]
Tbh I'll probably uninstall python and pycharm and reinstall.

**Comment by guojiahuiEmily** [comment]
only exist sc2pathlib.so, no sc2pathlib.dll.   maybe that's the reason.

**Comment by guojiahuiEmily** [comment]
It must use python3.7.  not work on other. and need compile the so on mac by yourself.
